
name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Init DB
        run: python scripts/init_db.py

      - name: Run tests
        run: |
          mkdir -p EVIDENCE/S08
          pytest -q --junitxml=EVIDENCE/S08/test-report.xml
        continue-on-error: false

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: evidence-s08
          path: |
            EVIDENCE/S08/**
          if-no-files-found: warn
